# run tests using the binary built before
test:
  stage: test
  script:
    - make check
    
debian_test:
  stage: deploy
  script: 
#    - rm -f *.{deb,dsc,changes}
    - dpkg-buildpackage --no-sign
#    - mv ../subverb*.{deb,dsc,changes} .
#  artifacts:
#    paths: 
#      - "*.deb"
#      - "*.dsc"
#      - "*.changes"
#    when: on_success
  only:
    - master

debian_upload:
  stage: deploy
  script:
    - rm ../subverb*.{deb,dsc,changes}
    - dpkg-buildpackage
    - reprepro includedeb experimental ../subverb*.deb
    - reprepro includedsc experimental ../subverb*.dsc
  only:
    - master
  when: manual
